---
- hosts: servers 
  vars:
   rest_user: "Administrator"
   rest_pass: "password"
   rest_port: 8091
   services: "data,index,query"
   ram_size: 1024 
   cli_bin:  "/couchbase-cli/couchbase-cli"
   internal_ip: "127.0.0.1"
   orchestrator:  "db1"
  remote_user: root
  tasks:
    - name: init data paths
      shell: "{{cli_bin}} node-init -c {{internal_ip}} -u {{rest_user}} -p {{rest_pass}}"
    - name: init cluster
      shell: "{{cli_bin}} cluster-init -c {{internal_ip}} --cluster-username={{rest_user}} --cluster-password={{rest_pass}} --cluster-port={{rest_port}} --cluster-ramsize={{ram_size}} --services={{services}}"
    - name: add node
      shell: "{{cli_bin}} server-add -c {{orchestrator}} --server-add={{internal_ip}}:{{rest_port}} --server-add-username={{rest_user}} --server-add-password={{rest_pass}} -u {{rest_user}} -p {{rest_pass}}"
      when: inventory_hostname != 'db1'


- hosts: db1 
  vars:
    rest_user: "Administrator"
    rest_pass: "password"
    cli_bin:  "/couchbase-cli/couchbase-cli"
  tasks:
    - name: rebalance
      shell: "{{cli_bin}} rebalance -c {{inventory_hostname}} -u {{rest_user}} -p {{rest_pass}}"

- hosts: db1 
  vars:
    rest_user: "Administrator"
    rest_pass: "password"
    bucket0: "bucket-1"
    bucket_size_main: 300 
    cli_bin:  "/couchbase-cli/couchbase-cli"
    internal_ip: "127.0.0.1"
  tasks:
   - name: create bucket0
     shell: "{{cli_bin}}  bucket-create -c  {{internal_ip}} -u {{rest_user}} -p {{rest_pass}} --bucket={{bucket0}} --bucket-ramsize={{bucket_size_main}} --bucket-type=couchbase --wait"


